{
    'name': "cash_denomination",
    'summary': "Cash Denomination",
    'description': "Cash Denomination",
    'category': 'Website',
    'version': '0.1',
    'depends': ['base','account','website','care_connector'],
    'data': [
        'security/ir.model.access.csv',
        'data/ir_sequence.xml',
        'views/cash_transfer_views.xml',
        'template/cash_denomination_template.xml',
        'template/denomination_register_template.xml',
        'template/payment_transaction_template.xml', 
        'template/denomination_history_menu.xml',
        'template/pending_cash_transfer.xml',
        'template/cash_accept_template.xml',
        'views/account_payment_views.xml',
        'views/cash_denomination_views.xml', 
        'views/account_head_config_views.xml',
        'wizard/cash_denomination_reject_reason_wizard.xml',
    ],
    'assets': {
            'web.assets_frontend': [
                'cash_denomination/static/src/css/website_service.css',
                'cash_denomination/static/src/js/cash_denomination_events.js',
                'cash_denomination/static/src/js/cash_denomination_register.js', 
                'cash_denomination/static/src/js/payment_transaction.js',
                'cash_denomination/static/src/js/pending_cash_transfer.js',
        ],
    },
    'installable': True,
    'auto_install': False,
    'application': False,
}